Repository jenkinsci/gitee-plugin, pull requests merged in 2025-05, with the labels that each got.

#87 Translations for pull request trigger values
  src/main/resources/com/gitee/jenkins/trigger/GiteePushTrigger/config.jelly
  src/main/resources/com/gitee/jenkins/trigger/GiteePushTrigger/config.properties
  src/main/resources/com/gitee/jenkins/trigger/GiteePushTrigger/config_zh_CN.properties
Labels: localization

#88 Bug fix for localization
  src/main/resources/com/gitee/jenkins/trigger/GiteePushTrigger/config_zh_CN.properties
Labels: bug

#89 Added GiteeConnectionConfigTest.java
  pom.xml
  src/test/java/com/gitee/jenkins/connection/GiteeConnectionConfigTest.java
Labels: tests

#90 Added Authentication tests to GiteeConnectionConfigTest.java
  pom.xml
  src/test/java/com/gitee/jenkins/connection/GiteeConnectionConfigTest.java
Labels: tests

#91 [Bugfix] Bug fix for web authentication
  src/main/java/com/gitee/jenkins/connection/GiteeConnectionConfig.java
  src/main/java/com/gitee/jenkins/webhook/build/BuildWebHookAction.java
  src/main/java/com/gitee/jenkins/webhook/build/NoteBuildAction.java
  src/main/java/com/gitee/jenkins/webhook/build/PipelineBuildAction.java
  src/main/java/com/gitee/jenkins/webhook/build/PullRequestBuildAction.java
  src/main/java/com/gitee/jenkins/webhook/build/PushBuildAction.java
  src/main/resources/com/gitee/jenkins/connection/GiteeConnectionConfig/config.jelly
  src/main/resources/com/gitee/jenkins/connection/GiteeConnectionConfig/config.properties
  src/main/resources/com/gitee/jenkins/connection/GiteeConnectionConfig/config_zh_CN.properties
  src/test/java/com/gitee/jenkins/connection/GiteeConnectionConfigTest.java
Labels: bug

#92 Revert Jackson 2.19.0 dependency to 2.18.3
  pom.xml
Labels: bug

#93 Added GiteeConnectionTest.java
  src/test/java/com/gitee/jenkins/connection/GiteeConnectionTest.java
Labels: test
